spring:
  application:
    name: homework5-service

  config:
    # Подключение к Spring Cloud Config
    import: optional:configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: karinaorlova656@gmail.com
    password: "tetn ufry vaha flod"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:h2:mem:homework5db
    driver-class-name: org.h2.Driver
    username: sa
    password:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  sendTestMail: false

server:
  port: 8080
