spring:
  application:
    name: homework5-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # позволяет автоматически проксировать сервисы через Eureka
      routes:
        - id: homework5-users
          uri: lb://HOMEWORK5-SERVICE
          predicates:
            - Path=/api/users/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
